### ISSUE TITLE
Content renders beneath titlbebar

### ISSUE THREAD

**Issue by theScrabi** [martykan/webTube#15]
Hello there,

I have a bug on my android 4.4.4 device, the content always renders beneath the title bar. Like this:
![screenshot_2016-01-08-22-33-20](https://cloud.githubusercontent.com/assets/1891273/12210381/c5390d5c-b659-11e5-8d60-15513fa07b8e.png)

**Comment by martykan** [comment]
I just fixed it a couple minutes ago. Should be on F-Droid next morning.

**Comment by theScrabi** [comment]
fast :)

**Comment by Yowlen** [comment]
This issue is still present for me. Running Kitkat 4.4.2. Happens with all app versions in the F-Droid repo from 0.7 up through the latest 1.0 release.
